<?php

return [
    'brands' => [
        'A-Toys by TOYFA',
        'Anonymo by TOYFA',
        'Beyond by Toyfa',
        'Black&Red by TOYFA',
        'Candy Girl',
        'Dolce by TOYFA',
        'Dolls-X by TOYFA',
        'Erolanta',
        'Erolanta Glossy',
        'Eromantica',
        'eroTEQ by TOYFA',
        'Erotist Adult Toys',
        'Erotist Hero',
        'Erotist Libido Booster',
        'Erotist Lubricant',
        'Jos',
        'Juicy Pussy by TOYFA',
        "L'Eroina",
        'Let it G',
        'Lingam by TOYFA',
        'Marcus by TOYFA',
        'Metal by TOYFA',
        'Motorlovers by TOYFA',
        'Mr.Baton by TOYFA',
        'My Babe by RealStick',
        "O'Play by TOYFA",
        'Pecado',
        'Physics by Toyfa',
        'POPO Pleasure by TOYFA',
        'Qli by Flovetta',
        'Qvibry',
        'RealStick Brutal',
        'RealStick Caliber',
        'RealStick Elite',
        'RealStick Elite Mulatto',
        'RealStick Nude',
        'RealStick Silicone',
        'RealStick Strap-On',

        'Sexus Glass',
        'Sexus Men',
        'Sosuсki',
        'Theatre by TOYFA',
        'ToDo by Toyfa',
        'TOYFA Basic',
        'Waname Apparel',
        'Waname D-splash',
        'Waname Lubricant',
        'XLover by TOYFA',
        'Yovee',
        'Штучки-Дрючки',
    ],
];
